spring:
  application:
    name: order-system

  datasource:
    url: jdbc:postgresql://localhost:5432/order_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: tx-
      acks: all
      retries: 3
      enable-idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer